"""update_lifecycle_to_jsonlist

Revision ID: 01a9e1791f8c
Revises: 0d489ae859a2
Create Date: 2026-02-11 21:19:48.933023

"""

# revision identifiers, used by Alembic.
revision = "01a9e1791f8c"
down_revision = "0d489ae859a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
