"""update_lifecycle_to_jsonlist

Revision ID: 0d489ae859a2
Revises: 1789d7838be8
Create Date: 2026-02-11 21:15:54.459167

"""

# revision identifiers, used by Alembic.
revision = "0d489ae859a2"
down_revision = "1789d7838be8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
