"""initial_fresh_start

Revision ID: 1789d7838be8
Revises:
Create Date: 2026-02-12 01:18:29.328849

"""

import sqlalchemy as sa
from alembic import op

import beenative

# revision identifiers, used by Alembic.
revision = "1789d7838be8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scientific_name", sa.String(), nullable=False),
        sa.Column("is_native", sa.Boolean(), nullable=True),
        sa.Column("common_names", beenative.models.base.JsonList(), nullable=True),
        sa.Column("sunlight", beenative.models.base.JsonList(), nullable=True),
        sa.Column("moisture", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_common_name", sa.String(), nullable=True),
        sa.Column("pm_catalog_code", sa.String(), nullable=True),
        sa.Column("pm_about", sa.String(), nullable=True),
        sa.Column("pm_image_url", sa.String(), nullable=True),
        sa.Column("pm_url", sa.String(), nullable=True),
        sa.Column("pm_bloom_color", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_bloom_time", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_life_cycle", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_native_states", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_height", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_sun_exposure", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_soil_moisture", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_germination_code", beenative.models.base.JsonList(), nullable=True),
        sa.Column("pm_adv_bee", sa.Boolean(), nullable=True),
        sa.Column("pm_adv_bird", sa.Boolean(), nullable=True),
        sa.Column("pm_adv_deer", sa.Boolean(), nullable=True),
        sa.Column("pm_adv_stars", sa.Boolean(), nullable=True),
        sa.Column("ncsu_url", sa.String(), nullable=True),
        sa.Column("ncsu_phonetic_spelling", sa.String(), nullable=True),
        sa.Column("ncsu_html_description", sa.String(), nullable=True),
        sa.Column("ncsu_description", sa.String(), nullable=True),
        sa.Column("ncsu_genus", sa.String(), nullable=True),
        sa.Column("ncsu_species", sa.String(), nullable=True),
        sa.Column("ncsu_family", sa.String(), nullable=True),
        sa.Column("ncsu_uses_ethnobotany", sa.String(), nullable=True),
        sa.Column("ncsu_life_cycle", sa.String(), nullable=True),
        sa.Column("ncsu_recommended_propagation_strategy", sa.String(), nullable=True),
        sa.Column("ncsu_country_or_region_of_origin", sa.String(), nullable=True),
        sa.Column("ncsu_distribution", sa.String(), nullable=True),
        sa.Column("ncsu_fire_risk_rating", sa.String(), nullable=True),
        sa.Column("ncsu_wildlife_value", sa.String(), nullable=True),
        sa.Column("ncsu_play_value", sa.String(), nullable=True),
        sa.Column("ncsu_particularly_resistant_to_insects_diseases_other_problems", sa.String(), nullable=True),
        sa.Column("ncsu_edibility", sa.String(), nullable=True),
        sa.Column("ncsu_habit_form", sa.String(), nullable=True),
        sa.Column("ncsu_growth_rate", sa.String(), nullable=True),
        sa.Column("ncsu_maintenance", sa.String(), nullable=True),
        sa.Column("ncsu_texture", sa.String(), nullable=True),
        sa.Column("ncsu_light", sa.String(), nullable=True),
        sa.Column("ncsu_soil_texture", sa.String(), nullable=True),
        sa.Column("ncsu_soil_ph", sa.String(), nullable=True),
        sa.Column("ncsu_soil_drainage", sa.String(), nullable=True),
        sa.Column("ncsu_available_space_to_plant", sa.String(), nullable=True),
        sa.Column("ncsu_nc_region", sa.String(), nullable=True),
        sa.Column("ncsu_usda_plant_hardiness_zone", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_color", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_value_to_gardener", sa.String(), nullable=True),
        sa.Column("ncsu_display_harvest_time", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_type", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_length", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_width", sa.String(), nullable=True),
        sa.Column("ncsu_fruit_description", sa.String(), nullable=True),
        sa.Column("ncsu_flower_color", sa.String(), nullable=True),
        sa.Column("ncsu_flower_inflorescence", sa.String(), nullable=True),
        sa.Column("ncsu_flower_bloom_time", sa.String(), nullable=True),
        sa.Column("ncsu_flower_size", sa.String(), nullable=True),
        sa.Column("ncsu_flower_description", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_color", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_feel", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_value_to_gardener", sa.String(), nullable=True),
        sa.Column("ncsu_deciduous_leaf_fall_color", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_type", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_arrangement", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_shape", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_margin", sa.String(), nullable=True),
        sa.Column("ncsu_hairs_present", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_length", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_width", sa.String(), nullable=True),
        sa.Column("ncsu_leaf_description", sa.String(), nullable=True),
        sa.Column("ncsu_bark_color", sa.String(), nullable=True),
        sa.Column("ncsu_surface_attachment", sa.String(), nullable=True),
        sa.Column("ncsu_bark_plate_shape", sa.String(), nullable=True),
        sa.Column("ncsu_bark_description", sa.String(), nullable=True),
        sa.Column("ncsu_stem_color", sa.String(), nullable=True),
        sa.Column("ncsu_stem_is_aromatic", sa.String(), nullable=True),
        sa.Column("ncsu_pith_split_longitudinally", sa.String(), nullable=True),
        sa.Column("ncsu_stem_description", sa.String(), nullable=True),
        sa.Column("ncsu_landscape_location", sa.String(), nullable=True),
        sa.Column("ncsu_landscape_theme", sa.String(), nullable=True),
        sa.Column("ncsu_design_feature", sa.String(), nullable=True),
        sa.Column("ncsu_attracts", sa.String(), nullable=True),
        sa.Column("ncsu_resistance_to_challenges", sa.String(), nullable=True),
        sa.Column("ncsu_appendage", sa.String(), nullable=True),
        sa.Column("ncsu_flower_value_to_gardener", sa.String(), nullable=True),
        sa.Column("ncsu_flower_shape", sa.String(), nullable=True),
        sa.Column("ncsu_flower_petals", sa.String(), nullable=True),
        sa.Column("ncsu_stem_surface", sa.String(), nullable=True),
        sa.Column("ncsu_problems", sa.String(), nullable=True),
        sa.Column("ncsu_poison_severity", sa.String(), nullable=True),
        sa.Column("ncsu_poison_symptoms", sa.String(), nullable=True),
        sa.Column("ncsu_poison_toxic_principle", sa.String(), nullable=True),
        sa.Column("ncsu_causes_contact_dermatitis", sa.String(), nullable=True),
        sa.Column("ncsu_poison_part", sa.String(), nullable=True),
        sa.Column("ncsu_stem_buds", sa.String(), nullable=True),
        sa.Column("ncsu_stem_bud_terminal", sa.String(), nullable=True),
        sa.Column("ncsu_stem_cross_section", sa.String(), nullable=True),
        sa.Column("ncsu_stem_form", sa.String(), nullable=True),
        sa.Column("ncsu_stem_lenticels", sa.String(), nullable=True),
        sa.Column("ncsu_climbing_method", sa.String(), nullable=True),
        sa.Column("ncsu_stem_bud_scales", sa.String(), nullable=True),
        sa.Column("ncsu_bulb_storage", sa.String(), nullable=True),
        sa.Column("ncsu_stem_leaf_scar_shape", sa.String(), nullable=True),
        sa.Column("ncsu_woody_plant_leaf_characteristics", sa.String(), nullable=True),
        sa.Column("ncsu_other_common_names", beenative.models.base.JsonList(), nullable=True),
        sa.Column("ncsu_cultivars", beenative.models.base.JsonList(), nullable=True),
        sa.Column("ncsu_dimensions", sa.JSON(), nullable=True),
        sa.Column("ncsu_plant_type", sa.String(), nullable=True),
        sa.Column("ncsu_images", sa.JSON(), nullable=True),
        sa.Column("vasc_id", sa.String(), nullable=True),
        sa.Column("vasc_common_name_primary", sa.String(), nullable=True),
        sa.Column("vasc_author", sa.String(), nullable=True),
        sa.Column("vasc_distribution", sa.String(), nullable=True),
        sa.Column("vasc_abundance", sa.String(), nullable=True),
        sa.Column("vasc_habitat", sa.String(), nullable=True),
        sa.Column("vasc_phenology", sa.String(), nullable=True),
        sa.Column("vasc_identification", sa.String(), nullable=True),
        sa.Column("vasc_taxonomic_comments", sa.String(), nullable=True),
        sa.Column("vasc_other_common_names", sa.String(), nullable=True),
        sa.Column("vasc_state_rank", sa.String(), nullable=True),
        sa.Column("vasc_global_rank", sa.String(), nullable=True),
        sa.Column("vasc_state_status", sa.String(), nullable=True),
        sa.Column("vasc_us_status", sa.String(), nullable=True),
        sa.Column("vasc_usace_agcp", sa.String(), nullable=True),
        sa.Column("vasc_usace_emp", sa.String(), nullable=True),
        sa.Column("vasc_map_file_path", sa.String(), nullable=True),
        sa.Column("vasc_map_file_url", sa.String(), nullable=True),
        sa.Column("ncbg_permalink", sa.String(), nullable=True),
        sa.Column("ncbg_images", sa.JSON(), nullable=True),
        sa.Column("vasc_other_common_names_clean", beenative.models.base.JsonList(), nullable=True),
        sa.Column("all_common_names", beenative.models.base.JsonList(), nullable=True),
        sa.Column("wildlife_attracts", beenative.models.base.JsonList(), nullable=True),
        sa.Column("plant_resistances", beenative.models.base.JsonList(), nullable=True),
        sa.Column("bloom_months", sa.JSON(), nullable=True),
        sa.Column("sunlight_categories", beenative.models.base.JsonList(), nullable=True),
        sa.Column("moisture_categories", beenative.models.base.JsonList(), nullable=True),
        sa.Column("primary_lifecycle", sa.String(), nullable=True),
        sa.Column("flower_colors", beenative.models.base.JsonList(), nullable=True),
        sa.Column("plant_categories", beenative.models.base.JsonList(), nullable=True),
        sa.Column("height_min_ft", sa.Float(), nullable=True),
        sa.Column("height_max_ft", sa.Float(), nullable=True),
        sa.Column("width_min_ft", sa.Float(), nullable=True),
        sa.Column("width_max_ft", sa.Float(), nullable=True),
        sa.Column("height_str", sa.String(), nullable=True),
        sa.Column("width_str", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plants_scientific_name"), ["scientific_name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plants_scientific_name"))

    op.drop_table("plants")
    # ### end Alembic commands ###
