"""Add provenance_status and provenance_notes to plant model

Revision ID: 254f6bea39e6
Revises: b3f49df8912f
Create Date: 2026-09-27 20:46:20.310673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "254f6bea39e6"
down_revision = "b3f49df8912f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provenance_status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("provenance_notes", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_plants_provenance_status"), ["provenance_status"], unique=False)
        batch_op.drop_column("is_native")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_native", sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_plants_provenance_status"))
        batch_op.drop_column("provenance_notes")
        batch_op.drop_column("provenance_status")

    # ### end Alembic commands ###
