"""Removing duplicative columns

Revision ID: 46df992b602f
Revises: 01a9e1791f8c
Create Date: 2026-02-28 23:13:24.204409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46df992b602f'
down_revision = '01a9e1791f8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('common_names')
        batch_op.drop_column('moisture')
        batch_op.drop_column('sunlight')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sunlight', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('moisture', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('common_names', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
