"""Moving to latest changes

Revision ID: b3f49df8912f
Revises: 46df992b602f
Create Date: 2026-03-12 19:56:00.279327

"""

# revision identifiers, used by Alembic.
revision = "b3f49df8912f"
down_revision = "46df992b602f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
