from sqlalchemy import Column, String, Boolean, Integer, JSON, Float
from .base import Base, JsonList


class Plant(Base):
    __tablename__ = "plants"

    # --- Primary Key & Core Identity ---
    id = Column(Integer, primary_key=True, autoincrement=True)
    scientific_name = Column(String, unique=True, nullable=False, index=True)
    is_native = Column(Boolean, default=True)

    # --- Prairie Moon Data (pm_*) ---
    pm_common_name = Column(String)
    pm_catalog_code = Column(String)
    pm_about = Column(String)
    pm_image_url = Column(String)
    pm_url = Column(String)
    # Lists
    pm_bloom_color = Column(JsonList)
    pm_bloom_time = Column(JsonList)
    pm_life_cycle = Column(JsonList)
    pm_native_states = Column(JsonList)
    pm_height = Column(JsonList)
    pm_sun_exposure = Column(JsonList)
    pm_soil_moisture = Column(JsonList)
    pm_germination_code = Column(JsonList)
    # Booleans
    pm_adv_bee = Column(Boolean)
    pm_adv_bird = Column(Boolean)
    pm_adv_deer = Column(Boolean)
    pm_adv_stars = Column(Boolean)

    # --- NCSU Plant Toolbox Data (ncsu_*) ---
    ncsu_url = Column(String)
    ncsu_phonetic_spelling = Column(String)
    ncsu_html_description = Column(String)
    ncsu_description = Column(String)
    ncsu_genus = Column(String)
    ncsu_species = Column(String)
    ncsu_family = Column(String)
    ncsu_uses_ethnobotany = Column(String)
    ncsu_life_cycle = Column(String)
    ncsu_recommended_propagation_strategy = Column(String)
    ncsu_country_or_region_of_origin = Column(String)
    ncsu_distribution = Column(String)
    ncsu_fire_risk_rating = Column(String)
    ncsu_wildlife_value = Column(String)
    ncsu_play_value = Column(String)
    ncsu_particularly_resistant_to_insects_diseases_other_problems = Column(String)
    ncsu_edibility = Column(String)
    ncsu_habit_form = Column(String)
    ncsu_growth_rate = Column(String)
    ncsu_maintenance = Column(String)
    ncsu_texture = Column(String)
    ncsu_light = Column(String)
    ncsu_soil_texture = Column(String)
    ncsu_soil_ph = Column(String)
    ncsu_soil_drainage = Column(String)
    ncsu_available_space_to_plant = Column(String)
    ncsu_nc_region = Column(String)
    ncsu_usda_plant_hardiness_zone = Column(String)
    ncsu_fruit_color = Column(String)
    ncsu_fruit_value_to_gardener = Column(String)
    ncsu_display_harvest_time = Column(String)
    ncsu_fruit_type = Column(String)
    ncsu_fruit_length = Column(String)
    ncsu_fruit_width = Column(String)
    ncsu_fruit_description = Column(String)
    ncsu_flower_color = Column(String)
    ncsu_flower_inflorescence = Column(String)
    ncsu_flower_bloom_time = Column(String)
    ncsu_flower_size = Column(String)
    ncsu_flower_description = Column(String)
    ncsu_leaf_color = Column(String)
    ncsu_leaf_feel = Column(String)
    ncsu_leaf_value_to_gardener = Column(String)
    ncsu_deciduous_leaf_fall_color = Column(String)
    ncsu_leaf_type = Column(String)
    ncsu_leaf_arrangement = Column(String)
    ncsu_leaf_shape = Column(String)
    ncsu_leaf_margin = Column(String)
    ncsu_hairs_present = Column(String)
    ncsu_leaf_length = Column(String)
    ncsu_leaf_width = Column(String)
    ncsu_leaf_description = Column(String)
    ncsu_bark_color = Column(String)
    ncsu_surface_attachment = Column(String)
    ncsu_bark_plate_shape = Column(String)
    ncsu_bark_description = Column(String)
    ncsu_stem_color = Column(String)
    ncsu_stem_is_aromatic = Column(String)
    ncsu_pith_split_longitudinally = Column(String)
    ncsu_stem_description = Column(String)
    ncsu_landscape_location = Column(String)
    ncsu_landscape_theme = Column(String)
    ncsu_design_feature = Column(String)
    ncsu_attracts = Column(String)
    ncsu_resistance_to_challenges = Column(String)
    ncsu_appendage = Column(String)
    ncsu_flower_value_to_gardener = Column(String)
    ncsu_flower_shape = Column(String)
    ncsu_flower_petals = Column(String)
    ncsu_stem_surface = Column(String)
    ncsu_problems = Column(String)
    ncsu_poison_severity = Column(String)
    ncsu_poison_symptoms = Column(String)
    ncsu_poison_toxic_principle = Column(String)
    ncsu_causes_contact_dermatitis = Column(String)
    ncsu_poison_part = Column(String)
    ncsu_stem_buds = Column(String)
    ncsu_stem_bud_terminal = Column(String)
    ncsu_stem_cross_section = Column(String)
    ncsu_stem_form = Column(String)
    ncsu_stem_lenticels = Column(String)
    ncsu_climbing_method = Column(String)
    ncsu_stem_bud_scales = Column(String)
    ncsu_bulb_storage = Column(String)
    ncsu_stem_leaf_scar_shape = Column(String)
    ncsu_woody_plant_leaf_characteristics = Column(String)
    # JSON/Lists
    ncsu_other_common_names = Column(JsonList)
    ncsu_cultivars = Column(JsonList)
    ncsu_dimensions = Column(JSON)
    ncsu_plant_type = Column(String)  # Stored as string, categorized later
    ncsu_images = Column(JSON)

    # --- Vascular NC Data (vasc_*) ---
    vasc_id = Column(String)
    vasc_common_name_primary = Column(String)
    vasc_author = Column(String)
    vasc_distribution = Column(String)
    vasc_abundance = Column(String)
    vasc_habitat = Column(String)
    vasc_phenology = Column(String)
    vasc_identification = Column(String)
    vasc_taxonomic_comments = Column(String)
    vasc_other_common_names = Column(String)  # Original messy string
    vasc_state_rank = Column(String)
    vasc_global_rank = Column(String)
    vasc_state_status = Column(String)
    vasc_us_status = Column(String)
    vasc_usace_agcp = Column(String)
    vasc_usace_emp = Column(String)
    vasc_map_file_path = Column(String)
    vasc_map_file_url = Column(String)

    # --- NC Botanical Garden Data (ncbg_*) ---
    ncbg_permalink = Column(String)
    ncbg_images = Column(JSON)

    # --- Derived / Processed Fields ---
    vasc_other_common_names_clean = Column(JsonList)
    all_common_names = Column(JsonList)
    wildlife_attracts = Column(JsonList)
    plant_resistances = Column(JsonList)
    bloom_months = Column(JSON)  # JSON Map of {Month: Weight}
    sunlight_categories = Column(JsonList)
    moisture_categories = Column(JsonList)
    primary_lifecycle = Column(JsonList)
    flower_colors = Column(JsonList)
    plant_categories = Column(JsonList)

    # Height/Width Stats
    height_min_ft = Column(Float)
    height_max_ft = Column(Float)
    width_min_ft = Column(Float)
    width_max_ft = Column(Float)
    height_str = Column(String)
    width_str = Column(String)
