name: Build Flet App

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

env:
  UV_PYTHON: 3.12
  PYTHONUTF8: 1

  # https://docs.flet.dev/reference/environment-variables
  FLET_CLI_NO_RICH_OUTPUT: 1
  USE_SYSTEM_PYTHON: true

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # -------- Desktop --------
          - name: linux
            runner: ubuntu-latest
            build_cmd: "flet build linux"
            artifact_path: build/linux

          - name: macos
            runner: macos-latest
            build_cmd: "flet build macos"
            artifact_path: build/macos

          # - name: windows
          #   runner: windows-latest
          #   build_cmd: "flet build windows"
          #   artifact_path: build/windows

          # -------- Android --------
          # - name: aab
          #   runner: ubuntu-latest
          #   build_cmd: "flet build aab"
          #   artifact_path: build/aab

          # - name: apk
          #   runner: ubuntu-latest
          #   build_cmd: "flet build apk"
          #   artifact_path: build/apk

          # -------- iOS --------
          # - name: ipa
          #   runner: macos-latest
          #   build_cmd: "flet build ipa"
          #   artifact_path: build/ipa

          # - name: ios-simulator
          #   runner: macos-latest
          #   build_cmd: "flet build ios-simulator"
          #   artifact_path: build/ios-simulator

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: make install

      - name: Install macOS System Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install libjpeg libtiff little-cms2 openjpeg webp
          # Ensure the compiler can find them
          echo "LDFLAGS=-L/opt/homebrew/opt/libjpeg/lib -L/opt/homebrew/opt/libtiff/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/opt/homebrew/opt/libjpeg/include -I/opt/homebrew/opt/libtiff/include" >> $GITHUB_ENV

      - name: Build app
        shell: bash
        run: |
          uv run ${{ matrix.build_cmd }} --build-number ${{ github.run_number }} --yes --verbose --skip-flutter-doctor

      - name: Upload Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: ${{ matrix.name }}-build-artifact
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
          overwrite: false
